services:
  - type: web
    name: pterodactyl-panel
    plan: standard
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_URL
        value: https://panel-hosting.onrender.com
      - key: DB_HOST
        fromService:
          name: pterodactyl-db
          type: postgres
          property: host
      - key: DB_PASSWORD
        fromService:
          name: pterodactyl-db
          type: postgres
          property: password
    port: 8080
    healthCheckPath: /
